name: "Docker Image Test"
on:
  workflow_dispatch:
  push:
    paths:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup QEMU # used to allow multiplatform docker builds
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx # used to allow multiplatform docker builds
      uses: docker/setup-buildx-action@v3
    - name: Test Firefox
      if: always()
      run: |
        testresult=$(docker run sitespeedio/sitespeed.io:35.0.0 -b firefox -n 1 https://webperf.se)
        echo "$testresult"
        path=$(echo "$testresult" | grep -o "/sitespeed.io/.*")
        echo "$path
        if [ -n "$path" ]; then
          har_file=$(find "$path" -name "browsertime.har")
          if [ -f "$har_file" ]; then
            echo "Found browsertime.har at $har_file"
            cat "$har_file"
          else
            echo "browsertime.har not found in $path"
          fi
        else
          echo "No path found starting with /sitespeed.io/"
        fi
